import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Carpas MM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='text-4xl text-red-600 text-center '>
        Carpas MM Web Page
      </div>
      
    </div>
  )
}
